pub mod accounts;
pub mod backup;
pub mod cleanbase;
pub mod companions;
pub mod client;
pub mod clientdl;
pub mod config;
pub mod console;
pub mod db;
pub mod diag;
pub mod docker;
pub mod download;
pub mod driver;
pub mod error;
pub mod firewall;
pub mod friends;
pub mod fsx;
pub mod health;
pub mod install;
pub mod layout;
pub mod logging;
pub mod pkgsource;
pub mod population;
pub mod process;
pub mod manifest;
pub mod migrations;
pub mod net;
pub mod package;
pub mod platform;
pub mod ra;
pub mod allsettings;
pub mod modules;
pub mod realmlist;
pub mod realms;
pub mod registry;
pub mod release;
pub mod update;
pub mod upnp;
pub mod signing;
pub mod srp6;

pub use error::{Error, ErrorCode, Result};

pub const MANAGER_VERSION: &str = env!("CARGO_PKG_VERSION");
